### ISSUE TITLE
Script creates playlists in parent folder

### ISSUE THREAD

**Issue by delta1071** [mattiasghodsian/PhinellyPort#3]
I run the script in the parent Music folder. The .m3u8 files are created in the parent folder. Ideally, each subfolder (or sub-subfolder) would contain a playlist for its own songs. My hierarchy is like this: 

Music  <-- m3u8 currently created here
     Duke Ellington
          16 Most Requested Songs  <--  create playlist here instead

**Comment by mattiasghodsian** [comment]
Do you want the script to place the `.m3u8` in  the corresponded sub folder instead ? am i understanding this correctly

**Comment by adubois-dev** [comment]
Hello,

Actually I have the same issue My music folder is this way

ls -l Playlists
total 2480
drwxrwxrwx 1 root root    8192 Oct  5 11:26  Celtique
drwxrwxrwx 1 root root  286720 Oct  5 11:32 'Chansons françaises à texte'
drwxrwxrwx 1 root root   40960 Oct  5 11:34  Duos
drwxrwxrwx 1 root root   49152 Oct  5 11:35  Electro
drwxrwxrwx 1 root root   45056 Oct  5 11:38  Japan
drwxrwxrwx 1 root root  282624 Sep 29 09:51 'Pop_Rock FR'
drwxrwxrwx 1 root root  241664 Oct  5 11:48 'Pop US'
drwxrwxrwx 1 root root  155648 Sep 29 00:50 'Punk_Rock FR'
drwxrwxrwx 1 root root   77824 Sep 29 09:53 'Rap FR'
drwxrwxrwx 1 root root   45056 Oct  5 11:52 'Rap US, Funk & R'\''n'\''B'
drwxrwxrwx 1 root root  126976 Sep 29 00:56 'Rock & Metal'
drwxrwxrwx 1 root root 1179648 Oct  5 12:34 'Titres Likés'

I would like each playlist to be generated in each subfolder instead of just putting all the playlists in the script folder with an absolute path.

This way, albums folder location can change but playlists remain OK because they use the files of the current folder they're generated in. Relative path instead of an absolute path

Hope you understand, my english is not what it used to be. If you have questions please let me know.

Regards,
Arnaud

**Comment by mattiasghodsian** [comment]
> Hello,
> 
> Actually I have the same issue My music folder is this way
> 
> ls -l Playlists total 2480 drwxrwxrwx 1 root root 8192 Oct 5 11:26 Celtique drwxrwxrwx 1 root root 286720 Oct 5 11:32 'Chansons françaises à texte' drwxrwxrwx 1 root root 40960 Oct 5 11:34 Duos drwxrwxrwx 1 root root 49152 Oct 5 11:35 Electro drwxrwxrwx 1 root root 45056 Oct 5 11:38 Japan drwxrwxrwx 1 root root 282624 Sep 29 09:51 'Pop_Rock FR' drwxrwxrwx 1 root root 241664 Oct 5 11:48 'Pop US' drwxrwxrwx 1 root root 155648 Sep 29 00:50 'Punk_Rock FR' drwxrwxrwx 1 root root 77824 Sep 29 09:53 'Rap FR' drwxrwxrwx 1 root root 45056 Oct 5 11:52 'Rap US, Funk & R'''n'''B' drwxrwxrwx 1 root root 126976 Sep 29 00:56 'Rock & Metal' drwxrwxrwx 1 root root 1179648 Oct 5 12:34 'Titres Likés'
> 
> I would like each playlist to be generated in each subfolder instead of just putting all the playlists in the script folder with an absolute path.
> 
> This way, albums folder location can change but playlists remain OK because they use the files of the current folder they're generated in. Relative path instead of an absolute path
> 
> Hope you understand, my english is not what it used to be. If you have questions please let me know.
> 
> Regards, Arnaud

i understand. ill look in to it
